export const VOTE_OPTIONS = Array.from(
  { length: 30 },
  (_, i) => `Option ${i + 1}`
);

// You can customize option names if needed
export const OPTION_NAMES = {
  "1": "PM마이크로 원가 혁신 및 신규폼팩터(MIC, MC02) 제품화",
  "2": "PM마이크로 모듈 공정혁신 기술 개발 (MIT)",
  "3": "AM 마이크로 LED CoW 얼룩 및 Black 감 개선",
  "4": "L3 Project",
  "5": "마이크로LED 저계조 화질 신규 규격 제정(TUV社)",
  "6": "PCB 배선 기술(PSV, Polarity Shared Via)",
  "7": "Magnit 리시빙보드 VI 기술",
  "8": "광원 특성 분석/반영을 통한 D-IC 저계조 개선",
  "9": "Stack 구조 D-IC 개발",
  "10": "In-Line Calibration System 구축 및 OTS(Optical Tracking Solution) 기술 개발",
  "11": "LGR(LED Gamma/Random error diffusion) 기술 개발",
  "12": "전면단차조절 구조를 통한 설치 편의성 개선",
  "13": "호텔 TV IoT Matter 지원",
  "14": "호텔 게스트 콘텐츠 사용 경험 개선",
  "15": "B2B LG Channels 개발",
  "16": "자체 색감 튜닝 전문 S/W 기능 개발",
  "17": "SW 개발 효율화를 위한 HDMI 통합 변환보드 개발",
  "18": "E-Paper 기반 Signage 개발",
  "19": "고휘도 사이니지  `세계최초` UL Verified 취득",
  "20": "회로도 표준화",
  "21": "전문가 모니터용 FPGA 화질보드 개발",
  "22": "마이크로 LED FOS 검사 플롯폼 개발",
  "23": "LED 생산지별 data 시각화 및 DB",
  "24": "고객 Casing 방열 예측 Simulator",
  "25": "LED 제품 피로 구조해석 기술",
  "26": "LED 열 팽창 구조 해석 기술",
  "27": "Video Switch IC-less DPM구현",
  "28": "Open API Test 자동화 Tool 개발",
  "29": "RCA (Root-Cause-Analysis) 개발",
  "30": "사이니지 출력 영상 오류 검출 서비스",
  "31": "광고 효과 측정을 위한 AI 엣지 플랫폼",
  "32": "사용자 음성 입력을 위한 초저가 Far-Field 마이크 디바이스",
  "33": "LG Shield 보안 제품 인증",
  "34": "Pro:Centric Cloud의 AirPlay 연동 개발",
  "35": "SuperSign Cloud 고도화 (멀티 OS 대응 및 광고 연동)",
  "36": "LG Business Cloud 개발",
  "37": "AI 챗봇 기반 B2B 고객 대응 서비스 제공",
  "38": "내장 LED 솔루션",
};
