export const VOTE_OPTIONS = Array.from({ length: 30 }, (_, i) => `Option ${i + 1}`);

// You can customize option names if needed
export const OPTION_NAMES = {
  'Option 1': '첫번째 선택지',
  'Option 2': '두번째 선택지',
  'Option 3': '세번째 선택지',
  'Option 4': '네번째 선택지',
  'Option 5': '다섯번째 선택지',
  'Option 6': '여섯번째 선택지',
  'Option 7': '일곱번째 선택지',
  'Option 8': '여덟번째 선택지',
  'Option 9': '아홉번째 선택지',
  'Option 10': '열번째 선택지',
  'Option 11': '열한번째 선택지',
  'Option 12': '열두번째 선택지',
  'Option 13': '열세번째 선택지',
  'Option 14': '열네번째 선택지',
  'Option 15': '열다섯번째 선택지',
  'Option 16': '열여섯번째 선택지',
  'Option 17': '열일곱번째 선택지',
  'Option 18': '열여덟번째 선택지',
  'Option 19': '열아홉번째 선택지',
  'Option 20': '스무번째 선택지',
  'Option 21': '스물한번째 선택지',
  'Option 22': '스물두번째 선택지',
  'Option 23': '스물세번째 선택지',
  'Option 24': '스물네번째 선택지',
  'Option 25': '스물다섯번째 선택지',
  'Option 26': '스물여섯번째 선택지',
  'Option 27': '스물일곱번째 선택지',
  'Option 28': '스물여덟번째 선택지',
  'Option 29': '스물아홉번째 선택지',
  'Option 30': '서른번째 선택지',
}; 